User:
  Username: "Boss"
Keys:
  OPEN_AI_API_KEY: "KEY_HERE"
  ELEVENLABS_API_KEY: "KEY_HERE"
Voices:
  useSystemVoice: True
  starterVoice: "Taron"
  currentVoice: "Taron"
Development:
  devEnvironment: True
  usingGUI: True
  usingLLM: True
  usingOperations: True
  usingVoice: True
